#!/bin/sh

if [ -z $MSYSTEM ]; then
  rg --files --type cpp src/nev | xargs clang-format -i
  rg --files --type cpp include/nev | xargs clang-format -i
  rg --files --type cpp demos | xargs clang-format -i
  rg --files --type cpp examples | xargs clang-format -i
  rg --files --type cpp contrib | xargs clang-format -i
else
  rg --path-separator '//' --files --type cpp src/nev | xargs clang-format -i
  rg --path-separator '//' --files --type cpp include/nev | xargs clang-format -i
  rg --path-separator '//' --files --type cpp demos | xargs clang-format -i
  rg --path-separator '//' --files --type cpp examples | xargs clang-format -i
  rg --path-separator '//' --files --type cpp contrib | xargs clang-format -i
fi
